version: "3.9"
name: exllama-api
services:
  api:
    image: exllama-api
    volumes:
      - D:/models:/data/model
      - D:/exllama:/app
    ports:
      - "8080:8080"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
